version: '3'

services:
  postgres:
      image: postgres
      container_name: movies-postgres-db
      environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
      ports:
          - '5432:5432'
      volumes:
          - ./.postgres-data:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./.redis-data:/data

volumes:
  postgres_data:
  redis_data: